"""adicionado subtotal ao item pedido

Revision ID: 421b8840f8b2
Revises: 8c7172be0b7e
Create Date: 2026-02-16 21:50:13.037910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '421b8840f8b2'
down_revision: Union[str, Sequence[str], None] = '8c7172be0b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itensPedido', sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_constraint(op.f('itensPedido_pedidoId_fkey'), 'itensPedido', type_='foreignkey')
    op.create_foreign_key(None, 'itensPedido', 'pedidos', ['pedidoId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'itensPedido', type_='foreignkey')
    op.create_foreign_key(op.f('itensPedido_pedidoId_fkey'), 'itensPedido', 'pedidos', ['pedidoId'], ['id'])
    op.drop_column('itensPedido', 'subtotal')
    # ### end Alembic commands ###
